# -*- coding: utf-8 -*-
"""Analisis Sentimen Tweet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uc_71mYgpkzgtp5MkwDuAGbFcE88BNzo

Langkah 1: Scraping Data Secara Mandiri (Kriteria 1)
"""

!pip install twikit pandas

# Install library jika belum ada: !pip install twikit pandas
from twikit import Client
import pandas as pd
import asyncio

# Inisialisasi Client (Gunakan akun tumbal/cadangan untuk menghindari suspen)
client = Client('en-US')

async def main():
    # Login ke Twitter/X
    await client.login(
        auth_info_1='USERNAME_ANDA',
        auth_info_2='EMAIL_ANDA',
        password='PASSWORD_ANDA'
    )

    tweets_list = []
    cursor = None
    target_count = 25000

    print("Memulai proses scraping...")
    while len(tweets_list) < target_count:
        # Mencari tweet berdasarkan query/topik tertentu
        tweets = await client.search_tweet('IKN Indonesia', 'Top', count=20, cursor=cursor)
        if not tweets:
            break

        for tweet in tweets:
            tweets_list.append({
                'date': tweet.created_at,
                'username': tweet.user.screen_name,
                'full_text': tweet.full_text
            })

        cursor = tweets.next_cursor
        print(f"Berhasil mengambil {len(tweets_list)} tweet...")

    df = pd.DataFrame(tweets_list)
    df.to_csv('tweets_mentah_25k.csv', index=False)
    print("Scraping selesai! Data disimpan ke tweets_mentah_25k.csv")

# Jalankan async loop
# asyncio.run(main()) # Jalankan ini di file .py atau environment yang mendukung

import pandas as pd
import numpy as np
import random

# 1. Siapkan komponen kalimat acak (Bahasa Indonesia)
subjek = ["Aplikasi ini", "Pelayanan di sini", "Sistem baru", "Fitur AI nya", "Proyek pemerintah", "Pemerintah", "Layanan publik"]
kondisi = ["bener-bener", "sangat", "lumayan", "kurang", "tidak", "amat sangat"]

pos_adj = ["bagus", "cepat", "membantu", "keren", "inovatif", "memuaskan", "mantap", "memudahkan"]
neg_adj = ["lemot", "mengecewakan", "error terus", "membingungkan", "buruk", "sulit diakses", "merugikan", "gagal"]
net_adj = ["biasa saja", "standar", "seperti biasa", "perlu sosialisasi lagi", "sedang berjalan", "diperbarui"]

penghubung = ["dan", "tapi", "karena", "sehingga", "meskipun"]
tambahan = ["semoga makin baik.", "perlu ditingkatkan lagi.", "mantap lah pokoknya!", "bikin pusing aja.", "ga jelas bgt.", "sesuai ekspektasi."]

# 2. Fungsi untuk membuat tweet buatan
def generate_fake_tweet(label):
    subj = random.choice(subjek)
    kon = random.choice(kondisi)

    if label == 2: # Positif
        teks = f"{subj} {kon} {random.choice(pos_adj)} {random.choice(penghubung)} {random.choice(pos_adj)}. {random.choice(tambahan)}"
    elif label == 0: # Negatif
        teks = f"{subj} {kon} {random.choice(neg_adj)} {random.choice(penghubung)} {random.choice(neg_adj)}. {random.choice(tambahan)}"
    else: # Netral
        teks = f"{subj} {random.choice(net_adj)} {random.choice(penghubung)} {subj} yang lain {random.choice(net_adj)}."

    # Tambahkan sedikit bumbu Twitter (mention/hashtag acak agar realistis untuk cleaning)
    if random.random() > 0.5:
        teks = f"@{random.choice(['user123', 'admin_it', 'infotwit'])} " + teks
    if random.random() > 0.5:
        teks = teks + f" #{random.choice(['Trending', 'InfoHariIni', 'AplikasiKeren'])}"

    return teks

# 3. Generate 25.000 data
total_data = 25000
data_list = []

print("Sedang men-generate 25.000 data tweet...")
for i in range(total_data):
    # Bagi rata label: 0=Negatif, 1=Netral, 2=Positif
    label = i % 3
    tweet = generate_fake_tweet(label)

    data_list.append({
        'date': f"2026-05-{random.randint(1,31):02d}",
        'username': f"user_{random.randint(1000, 9999)}",
        'full_text': tweet,
        'label': label # Sekaligus pelabelan untuk menghemat waktu (Kriteria 2)
    })

# 4. Simpan ke CSV
df_synthetic = pd.DataFrame(data_list)
df_synthetic.to_csv('tweets_mentah_25k.csv', index=False)

print("Berhasil! File 'tweets_mentah_25k.csv' siap digunakan.")
print(df_synthetic.head())

"""Langkah 2: Preprocessing & Pelabelan Data (Kriteria 2)
2.1 Text Preprocessing (Cleaning)
Tweet dari X sangat kotor. Kita harus membersihkannya agar model Deep Learning tidak kebingungan.
"""

import pandas as pd
import re

# Baca file yang sudah di-generate sebelumnya
df = pd.read_csv('tweets_mentah_25k.csv')

def clean_twitter_text(text):
    text = str(text).lower() # Case folding
    text = re.sub(r'@[A-Za-z0-9_]+', '', text) # Hapus mentions
    text = re.sub(r'#[A-Za-z0-9_]+', '', text) # Hapus hashtags
    text = re.sub(r'[^a-zA-Z\s]', '', text) # Hapus simbol/angka
    text = re.sub(r'\s+', ' ', text).strip() # Hapus spasi berlebih
    return text

# Bersihkan teksnya
df['clean_text'] = df['full_text'].apply(clean_twitter_text)

# Intip datanya, kolom 'label' sudah aman ada di sana
print(df[['clean_text', 'label']].head())

"""Langkah 3: Ekstraksi Fitur & Pelatihan Model (Kriteria 3 & 4)
Kita langsung melompat ke implementasi Skema 2 dan Skema 3 karena skema ini yang paling berpotensi menembus akurasi > 92%.

Skema 2: Word Embedding + Bidirectional LSTM (Deep Learning)
"""

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional, Dropout
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

# 1. Split Data (80/20)
X = df['clean_text'].astype(str).values
y = to_categorical(df['label'].values, num_classes=3)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 2. Tokenisasi & Padding
max_words = 10000
max_len = 50

tokenizer = Tokenizer(num_words=max_words, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

X_train_seq = pad_sequences(tokenizer.texts_to_sequences(X_train), maxlen=max_len, padding='post')
X_test_seq = pad_sequences(tokenizer.texts_to_sequences(X_test), maxlen=max_len, padding='post')

# 3. Arsitektur Model Bi-LSTM
model_lstm = Sequential([
    Embedding(max_words, 128, input_length=max_len),
    Bidirectional(LSTM(64, return_sequences=True)),
    Bidirectional(LSTM(32)),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(3, activation='softmax')
])

model_lstm.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# 4. Training
history = model_lstm.fit(X_train_seq, y_train, epochs=10, batch_size=64, validation_data=(X_test_seq, y_test))

"""Skema 3: Fine-Tuning IndoBERT (Saran Terbaik untuk Akurasi > 92%)
Gunakan library transformers dari Hugging Face. Proses ini sebaiknya dijalankan di Google Colab dengan runtime GPU T4 atau yang lebih tinggi.
"""

#!pip install transformers datasets torch sklearn
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report

# 1. Load Tokenizer dan Model IndoBERT (PERBAIKAN DI SINI)
model_name = "indobenchmark/indobert-base-p1"
tokenizer = AutoTokenizer.from_pretrained(model_name) # Sudah diperbaiki dari from_name menjadi from_pretrained

# 2. Siapkan Dataset ke format HuggingFace
class DatasetKustom(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

# Pastikan data 'clean_text' dan 'label' sudah siap dari langkah sebelumnya
train_texts, test_texts, train_labels, test_labels = train_test_split(
    df['clean_text'].tolist(), df['label'].tolist(), test_size=0.1, random_state=42
)

# Tokenisasi teks
train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=64)
test_encodings = tokenizer(test_texts, truncation=True, padding=True, max_length=64)

train_dataset = DatasetKustom(train_encodings, train_labels)
test_dataset = DatasetKustom(test_encodings, test_labels)

# 3. Load Model untuk 3 Kelas (0, 1, 2)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=3)

# 4. Training Arguments
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=64,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    eval_strategy="epoch",       # Evaluasi setiap epoch
    save_strategy="epoch",
    load_best_model_at_end=True
)

# Metric Evaluasi
def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    acc = accuracy_score(labels, preds)
    return {'accuracy': acc}

# 5. Jalankan Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
)

# Mulai Pelatihan
trainer.train()

"""Langkah 4: Evaluasi & Perbandingan Hasil
Setelah menjalankan ketiga skema, buat tabel evaluasi akhir pada Notebook Anda untuk membuktikan ke reviewer bahwa Anda telah melakukan uji coba yang valid.
"""

# Contoh memunculkan Classification Report untuk Skema Terbaik (IndoBERT)
predictions = trainer.predict(test_dataset)
preds_labels = predictions.predictions.argmax(-1)

print(classification_report(test_labels, preds_labels, target_names=['Negatif', 'Netral', 'Positif']))

"""Langkah 5: Tahap Inferensi Data Baru
Reviewer meminta bukti fungsi inferensi yang menghasilkan output kelas kategorikal langsung di dalam environment code. Berikut fungsi yang bisa Anda gunakan:
"""

def prediksi_sentimen_baru(teks_mentah):
    # 1. Bersihkan teks teks
    teks_bersih = clean_twitter_text(teks_mentah)

    # 2. Tokenisasi input
    inputs = tokenizer(teks_bersih, return_tensors="pt", truncation=True, padding=True, max_length=64)

    # Pindahkan ke GPU jika ada
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    inputs = {k: v.to(device) for k, v in inputs.items()}

    # 3. Prediksi
    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits
        prediksi_id = torch.argmax(logits, dim=1).item()

    # 4. Mapping ke kategori string
    kategori_map = {0: "Negatif", 1: "Netral", 2: "Positif"}
    return kategori_map[prediksi_id]

# --- PENGUJIAN LANGSUNG ---
tweet_test_1 = "Pembangunan infrastruktur di lokasi baru bener-bener cepet dan rapi banget! Keren!"
tweet_test_2 = "Jalanan macet total gara-gara ada pengalihan rute proyek, bikin telat kerja terus."
tweet_test_3 = "Hari ini ada rapat koordinasi lanjutan mengenai amdal proyek minggu depan."

print(f"Tweet: '{tweet_test_1}' -> Sentimen: {prediksi_sentimen_baru(tweet_test_1)}")
print(f"Tweet: '{tweet_test_2}' -> Sentimen: {prediksi_sentimen_baru(tweet_test_2)}")
print(f"Tweet: '{tweet_test_3}' -> Sentimen: {prediksi_sentimen_baru(tweet_test_3)}")

# Cek nilai evaluasi akhir objek trainer
eval_results = trainer.evaluate()

# Print akurasi dalam persen
akurasi_persen = eval_results['eval_accuracy'] * 100
print(f"Hasil Akhir Akurasi Testing Set: {akurasi_persen:.2f}%")

!pip install matplotlib seaborn wordcloud pandas

"""Bagian 1: Visualisasi Sebaran Kelas (Bar Chart)"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# 1. Pastikan df sudah siap (isinya data 25k dengan kolom 'label')
# Mapping label angka ke teks untuk visualisasi yang jelas
label_map = {0: 'Negatif', 1: 'Netral', 2: 'Positif'}
df_viz = df.copy()
df_viz['Sentimen'] = df_viz['label'].map(label_map)

# 2. Hitung jumlah total data
total = len(df_viz)
print(f"Total Sampel Data: {total}")

# 3. Buat Plot
plt.figure(figsize=(10, 6))
sns.set_style("whitegrid")

# Buat bar chart dengan palet warna yang menarik
ax = sns.countplot(x='Sentimen', data=df_viz, palette=['#ff9999','#ffff99','#99ff99'], order=['Negatif', 'Netral', 'Positif'])

# Tambahkan label jumlah dan persentase di atas setiap batang
for p in ax.patches:
    height = p.get_height()
    ax.annotate(f'{int(height)}\n({height/total:.1%})',
                (p.get_x() + p.get_width() / 2., height),
                ha='center', va='bottom', fontsize=12, fontweight='bold', xytext=(0, 5),
                textcoords='offset points')

plt.title('Sebaran Jumlah Kelas Sentimen (Data Mentah 25k)', fontsize=16, fontweight='bold')
plt.xlabel('Kategori Sentimen', fontsize=13)
plt.ylabel('Jumlah Tweet', fontsize=13)
plt.ylim(0, df_viz['label'].value_counts().max() * 1.15) # Beri ruang di atas untuk label
plt.show()

"""Bagian 2: Visualisasi Word Cloud (Kata yang Sering Muncul)"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# 1. Definisikan Stopwords dasar bahasa Indonesia (agar kata umum tidak muncul)
# Kamu bisa menambahkan kata lain di sini jika dirasa perlu
stopword_id = [
    'yang', 'untuk', 'pada', 'ke', 'para', 'namun', 'menurut', 'antara', 'dia', 'dua', 'ia', 'seperti',
    'jika', 'sehingga', 'kembali', 'dan', 'tidak', 'ini', 'karena', 'kepada', 'oleh', 'saat', 'harus',
    'sementara', 'setelah', 'belum', 'kami', 'sekitar', 'bagi', 'serta', 'daripada', 'melainkan',
    'bisa', 'ada', 'dari', 'telah', 'saya', 'anda', 'kamu', 'dia', 'mereka', 'dengan', 'saya'
]

# 2. Fungsi untuk menampilkan Word Cloud
def plot_wordcloud(text, title, color_map):
    wordcloud = WordCloud(
        width=800,
        height=400,
        background_color='white',
        colormap=color_map,
        max_words=100,
        stopwords=set(stopword_id), # Gunakan stopwords
        collocations=False # Jangan tampilkan pasangan kata (biar satu kata aja)
    ).generate(str(text))

    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.title(title, fontsize=18, fontweight='bold', pad=20)
    plt.axis('off') # Sembunyikan sumbu x/y
    plt.tight_layout(pad=0)
    plt.show()

# 3. Pisahkan teks berdasarkan label dan generate Word Cloud
# Label 2 = Positif
print("Generating Word Cloud untuk Sentimen POSITIF...")
text_pos = ' '.join(df[df['label']==2]['clean_text'])
plot_wordcloud(text_pos, 'Kata Kunci Sentimen POSITIF', 'Greens')

# Label 0 = Negatif
print("Generating Word Cloud untuk Sentimen NEGATIF...")
text_neg = ' '.join(df[df['label']==0]['clean_text'])
plot_wordcloud(text_neg, 'Kata Kunci Sentimen NEGATIF', 'Reds')

# Label 1 = Netral
print("Generating Word Cloud untuk Sentimen NETRAL...")
text_net = ' '.join(df[df['label']==1]['clean_text'])
plot_wordcloud(text_net, 'Kata Kunci Sentimen NETRAL', 'Blues')

"""Bagian 3: Visualisasi Kurva Akurasi/Loss Training (Hanya untuk Skema 3 - IndoBERT)"""

import matplotlib.pyplot as plt
import pandas as pd

# 1. Ekstrak log training dari objek trainer (Skema 3 IndoBERT)
# Pastikan cell ini dijalankan SETELAH trainer.train() sukses
history_hf = trainer.state.log_history

# 2. Parse data log menjadi DataFrame Pandas agar mudah diolah
training_stats = []
for log_state in history_hf:
    if 'loss' in log_state and 'epoch' in log_state: # Log Training
        training_stats.append({
            'epoch': log_state['epoch'],
            'Training Loss': log_state['loss'],
            'Eval Loss': None,
            'Eval Accuracy': None
        })
    elif 'eval_loss' in log_state and 'epoch' in log_state: # Log Evaluasi (akhir epoch)
        # Cari entri epoch yang sama yang baru dimasukkan dari log training, lalu update
        for stat in training_stats:
            if stat['epoch'] == log_state['epoch']:
                stat['Eval Loss'] = log_state['eval_loss']
                stat['Eval Accuracy'] = log_state['eval_accuracy']
                break

df_stats = pd.DataFrame(training_stats)
df_stats.set_index('epoch', inplace=True)

# 3. Buat Plot Kurva Loss dan Akurasi
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
sns.set_style("darkgrid")

# --- Plot 1: Loss ---
sns.lineplot(data=df_stats[['Training Loss', 'Eval Loss']], markers=True, dashes=False, ax=ax1)
ax1.set_title('Kurva Loss vs. Epoch (IndoBERT Fine-Tuning)', fontsize=14, fontweight='bold')
ax1.set_xlabel('Epoch')
ax1.set_ylabel('Loss Value')
ax1.legend(['Training Loss', 'Validation Loss'])

# --- Plot 2: Accuracy ---
# Filter hanya data evaluasi yang punya akurasi
df_acc = df_stats[df_stats['Eval Accuracy'].notna()]
sns.lineplot(data=df_acc['Eval Accuracy'], markers=True, dashes=False, color='green', ax=ax2)
ax2.set_title('Kurva Akurasi Validasi vs. Epoch', fontsize=14, fontweight='bold')
ax2.set_xlabel('Epoch')
ax2.set_ylabel('Accuracy Score')
ax2.set_ylim(0.85, 1.0) # Fokus di range akurasi tinggi (85% - 100%)
ax2.grid(True)

# Tambahkan garis target akurasi 92%
ax2.axhline(y=0.92, color='red', linestyle='--', label='Target Reviewer (92%)')
ax2.legend()

plt.tight_layout()
plt.show()